{"name": "Artarad Kadolin Custom",
 "summary": "سفارشی‌سازی‌های مخصوص مشتری کادولین (Odoo 18)",
 "description": "\n    مجموعه تغییرات و الحاقات سفارشی برای مشتری کادولین.\n    این ماژول در چند مرحله و به‌صورت افزایشی توسعه داده می‌شود.\n    ",
 "version": "18.0.1.0.1",
 "author": "Artadoo Team",
 "website": "https://artadoo.ir",
 "category": "Customization",
 "license": "LGPL-3",
 "application": False,
 "installable": True,
 "sequence": 100,
 "depends": ["base", "web", "product", "quality_control", "website_sale",
             "stock","rating","http_routing","loyalty","artarad_web_persian_calendar"],

 "data": [
     "security/ir.model.access.csv",
     "views/menu.xml",
     "views/product_views.xml",
     "views/quality_check_tree_akc.xml",
     "views/product_views_limit.xml",
     "views/stock.xml",
     "views/sale.xml",
     "views/package.xml",
     "views/website_templates.xml",
     "views/res_config_settings_views.xml",
     "data/reusable_packages.xml",
     "report/report.xml",
     "report/stock.xml",
     "report/sale_order.xml",


 ],
 "assets": {"web.assets_backend": ["artarad_kadolin_custom/static/src/css/akc_backend.css",
                                   "artarad_kadolin_custom/static/src/js/akc_placeholder.js",
                                   # "artarad_kadolin_custom/static/src/js/filter_feedback.js",
                                   # "artarad_kadolin_custom/static/src/css/filter_feedback.scss"
                                   ],
            "web.assets_frontend": [
                "artarad_kadolin_custom/static/src/css/akc_frontend.css",
                # "artarad_kadolin_custom/static/src/js/neshan_checkout.js",
                "artarad_kadolin_custom/static/src/js/delivery_slot_checkout.js",
                "artarad_kadolin_custom/static/src/js/neshan_tehran_map.js",
                "artarad_kadolin_custom/static/src/js/checkout_city_by_state.js",
                                    ]},
 }
