from . import res_config_settings
from . import product_template
from . import quality_list_buttons
from . import product_product
from . import stock
from . import stock_picking_type
from . import stock_move
from . import rating
from . import sale
